name: ui
description: Flutter UI components
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  cupertino_icons: ^1.0.8
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  assets:
    - assets/icons/